### ISSUE TITLE
I don't understand the code

### ISSUE THREAD

**Issue by ViaCognita** [blenderfan/AdvancedGamedevTutorials#1]
Hi!

I'm reading the code in **AdvancedGamedevTutorials/AdvancedGamedev-WindingNumbers/Polygon2D.cs** code and I don't understand the **line 22**.

Why do you do this `[(i + 1) % this.points.Count]`? Why do you use the modulus operator here? Are you looking for a specific vertex?

The only reason I can think of to use the module is because the vertices are ordered and you know where each one is. But I haven't found any mention that the vertices need to be ordered.

Thanks.

**Comment by blenderfan** [comment]
They are ordered in this version of the code (as polygons usually are). But if you have a different structure you might not need it.
